name: 'Setup run-job'
description: 'Install and authorize run-job'
branding:
  icon: box
  color: green
inputs:
  version:
    description: 'Version of run-job to install (tip, latest-release, v0.1, etc.)'
    required: true
    default: 'latest-release'
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      set -ex

      # Install run-job:
      # - if version is "tip", install from tip of main.
      # - if version is "latest-release", look up latest release.
      # - otherwise, install the specified version.
      case ${{ inputs.version }} in
      tip)
        echo "Installing run-job using go install"
        go install github.com/alexellis/run-job@main
        ;;
      latest-release)
        tag=$(curl -L -s -u "username:${{ github.token }}" https://api.github.com/repos/alexellis/run-job/releases/latest | jq -r '.tag_name')
        ;;
      *)
        tag="${{ inputs.version }}"
      esac

      os=${{ runner.os }}
      if [[ $os == "macOS" ]]; then
        os="-darwin"
      fi

      case ${{ runner.os }} in
      Linux)
        os=""
        ;;
      Windows)
        os=".exe"
        ;;
      Darwin)
        os="-darwin"
        ;;
      *)
        echo "Not adjusting OS Type ${os} for artifact"
      esac

      if [[ ! -z ${tag} ]]; then
        echo "Installing run-job @ ${tag} for ${os}"
        rm -f "${{ runner.temp }}/run-job" || return 0
        curl -fsL https://github.com/alexellis/run-job/releases/download/${tag}/run-job -o "${{ runner.temp }}/run-job"
        chmod a+x "${{ runner.temp }}/run-job"
        sudo mv "${{ runner.temp }}/run-job" "/usr/local/bin/run-job"    
      fi