name: mdlint
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  mdlint:
    name: mdlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: '0'
    - name: Install Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
    - name: Install shfmt
      run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
    - name: install dependencies
      run: |
        pip install --user mdformat mdformat-gfm mdformat-shfmt mdformat-tables mdformat-toc
        # linkify-it-py needed rust so I skipped it
    - name: markdown
      run: |
        export PATH="/root/.local/bin:$PATH"
        find . -type d -name node_modules -prune -o -name '*.md' -type f -print0 | xargs -0 -n1 -P4 mdformat --check --wrap keep --number
