name: Use Action

on:
  push:
    branches:
      - 'main'

jobs:
  use-action:
    name: Use Action

    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.20'
          check-latest: 'true'

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: StevenACoffman/setup-run-job@main
      - run: run-job version

      - name: Install old release
        uses: StevenACoffman/setup-run-job@main
        with:
          version: v0.0.0

      - run: run-job version
      - name: Check installed version
        run: run-job version | grep 0.8.0

      - name: Install from tip
        uses: StevenACoffman/setup-run-job@main
        with:
          version: tip

      - name: Check installed version (tip)
        run: |
          sudo rm /usr/local/bin/run-job # Uninstall previous versions.
          run-job version
