name: Use Action
on:
  push:
    branches:
    - 'main'
jobs:
  use-action:
    # runs-on: [self-hosted, linux, x64]
    timeout-minutes: 30
    permissions:
      # needed for the checkout action
      contents: read
      # needed to annotate the files in a pull request with comments
      pull-requests: write
    name: Use Action
    strategy:
      matrix:
        platform:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: '1.24'
        check-latest: 'true'
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        persist-credentials: "false"
    - uses: StevenACoffman/setup-run-job@c461223f2d28d6e774ece6ee8cb2105ea3d486f1 # main
    - run: which run-job
    - name: Install old release
      uses: StevenACoffman/setup-run-job@e2cc572430857f028c6fedaa7689a61fe9fe626a # v0.0.4
      with:
        version: 0.1.2
    - run: which run-job
    - name: Check installed version
      run: which run-job
    - name: Install from tip
      uses: StevenACoffman/setup-run-job@c461223f2d28d6e774ece6ee8cb2105ea3d486f1 # main
      with:
        version: tip
    - name: Check installed version (tip)
      run: |
        sudo rm /usr/local/bin/run-job # Uninstall previous versions.
        run-job version
